"""The `FormattedTextData` template for synthesized captions.

Generated by `scripts/dev/gen_caption_template.py` from 29_captions:
the head/tail around the text block, and the offset words (signed
FlatBuffer vtable offsets included) that shift with the padded
text length. The generator refuses to emit this module unless the
template rebuilds the fixture's own second payload byte-for-byte.
"""

import base64

PAYLOAD_HEAD = base64.b64decode(
    "1AEAAAAAAABEMyIRDAAAAAAABgAKAAQABgAAAGQAAAAAAF4ATAAUABAAAAAAAEgARAAAAAAAAAAAAEAAPwA4AAAANAAwACwAKAAAACQAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAADwAAAAgAAAAAAB8ABwBeAAAAAAAAAUQAAAAAAAABgAAAAJgAAAA8AAAAAAAAAAAAIEEAAAAAWAAAAAAAQEEAAMBAAABAQAAAyEIAAAABSAAAAAIAAAACAAAA9P7///j+//8BAAAADAAAAAAABgAIAAQABgAAAAQAAAANAAAAQW5pbWF0aW9uVHlwZQAAADr///8AAAAAQv///wAAAAABAAAABAAAAA0AAABMdWNpZGFDb25zb2xlAAAAAQAAAAwAAAAIAAwABAAIAAgAAAAIAAAAWAAAAA=="
)
PAYLOAD_TAIL = base64.b64decode(
    "AAA2ABwAAAAYAAAAAAAUAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAgABAA2AAAAAgAAABQAAAAYAAAAAAAAACAAAAAAAEBC4P///wQABgAEAAAAAAAKAAgABQAGAAcACgAAAAAAAAAEAAQABAAAAA=="
)

#: Byte offsets of the u32 words in PAYLOAD_HEAD that shift with
#: the padded text length: SHIFT_UP grow with it (the first is the
#: leading size header), SHIFT_DOWN are the signed vtable offsets
#: that point backward across the block and grow more negative.
SHIFT_UP = (0, 324)
SHIFT_DOWN = (204, 208, 256, 264)

#: The template text's padded block length (22 chars).
TEMPLATE_PADDED = 24

#: The static CaptionCollection settings JSON and stream fourcc.
COLLECTION_METADATA = '{"mCaptionsAreaRatio":0.800000011920929,"mCopyright":"","mData":"","mDescription":"","mEasyReader":false,"mLanguage":"","mLanguageCode":0,"mLanguageGroup":5,"mMaxCharactersInRow":40,"mMaxNumberOfRow":24,"mSmpteBeginTime":-101606400000000000,"mSmpteDataEncoding":"","mSmpteDataType":"","mTimeBase":0,"mTitle":""}'
STREAM_FORMAT = "1330660686"

#: The constant modification-state blob every synthetic
#: caption Media shares by hash: (BinaryHash, base64).
SYNTHETIC_STATE = (
    "b676125b-5f2c-0cc0-bf7e-72a40000001c",
    "QBmI+PSXgyUvAzukAAAAUA==",
)

#: The default caption style template a created track
#: carries: (BinaryHash, base64 payload).
TEMPLATE_STYLE = (
    "42ca7bc6-4d69-6f37-64c0-12690000018c",
    "dAEAAAAAAABEMyIRDAAAAAAABgAKAAQABgAAAGQAAAAAAF4APAAUABAAAAAAADgANAAAAAAAAAAAADAALwAoAAAAJAAgABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAgAAAAAABsABwBeAAAAAAAAATQAAAAAAAABUAAAAGgAAAAAAAAAAABAQQAAwEAAAEBAAADIQgAAAAEoAAAAAgAAAAIAAABE////SP///wQABgAEAAAAAAAKAAgABQAGAAcACgAAAAAAAAABAAAABAAAAA0AAABMdWNpZGFDb25zb2xlAAAAAQAAAAwAAAAIAAwABAAIAAgAAAAIAAAAQAAAAAEAAABhADYAGAAAABQAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAACAAEADYAAAACAAAAEAAAABAAAAAAAIBAAABAQvT////4/////P///wQABAAEAAAA",
)
