"""Premiere's default `AEMask2` mask component, read off
26_effect_mask - both roles carry the identical parameter set.

Generated by `scripts/dev/gen_mask_template.py`; regenerate after
the fixture changes (a unit test guards drift). The binary
payloads (Tracker, User Interactions, filter private data) are
opaque default-state blobs carried verbatim.
"""

MASK_CLASS_ID = "d10da199-beea-4dd1-b941-ed3a78766d50"
MASK_VERSION = "9"

#: `PremiereFilterPrivateData`: (BinaryHash, base64 payload).
PRIVATE_DATA = (
    "801239b7-73d1-ddc5-2fb7-1cc30000007c",
    "a2NpbgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDl+f//////AQAAAAAAAACA5fn//////wEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
)

#: (tag, ClassID, Version, fields) per parameter, in Params order;
#: fields are (child_tag, text, attrs). Values are the CLIP-role
#: defaults (neutral 0:0 geometry, empty path, full payloads).
MASK_PARAMS = (
    (
        "VideoComponentParam",
        "cc12343e-f113-4d3b-ae05-b287db77d461",
        "10",
        (
            ("ParameterControlType", "11", None),
            ("ParameterID", "1", None),
            ("StartKeyframe", "-91445760000000000,false,0,0,0,0,0,0", None),
            ("UpperBound", "false", None),
        ),
    ),
    (
        "VideoComponentParam",
        "cc12343e-f113-4d3b-ae05-b287db77d461",
        "10",
        (
            ("ParameterControlType", "16", None),
            ("ParameterID", "2", None),
            ("StartKeyframe", "-91445760000000000,false,0,0,0,0,0,0", None),
        ),
    ),
    (
        "VideoComponentParam",
        "cc12343e-f113-4d3b-ae05-b287db77d461",
        "10",
        (
            ("ParameterControlType", "16", None),
            ("ParameterID", "3", None),
            ("StartKeyframe", "-91445760000000000,false,0,0,0,0,0,0", None),
        ),
    ),
    (
        "VideoComponentParam",
        "cc12343e-f113-4d3b-ae05-b287db77d461",
        "10",
        (
            ("ParameterControlType", "16", None),
            ("ParameterID", "4", None),
            ("StartKeyframe", "-91445760000000000,false,0,0,0,0,0,0", None),
        ),
    ),
    (
        "VideoComponentParam",
        "cc12343e-f113-4d3b-ae05-b287db77d461",
        "10",
        (
            ("ParameterControlType", "16", None),
            ("ParameterID", "19", None),
            ("StartKeyframe", "-91445760000000000,false,0,0,0,0,0,0", None),
        ),
    ),
    (
        "VideoComponentParam",
        "cc12343e-f113-4d3b-ae05-b287db77d461",
        "10",
        (
            ("ParameterControlType", "16", None),
            ("ParameterID", "20", None),
            ("StartKeyframe", "-91445760000000000,false,0,0,0,0,0,0", None),
        ),
    ),
    (
        "VideoComponentParam",
        "cc12343e-f113-4d3b-ae05-b287db77d461",
        "10",
        (
            ("ParameterControlType", "12", None),
            ("ParameterID", "5", None),
            ("StartKeyframe", "-91445760000000000,false,0,0,0,0,0,0", None),
            ("UpperBound", "false", None),
        ),
    ),
    (
        "ArbVideoComponentParam",
        "313e54d4-6903-49ad-b0bf-8262cdd10f4e",
        "3",
        (
            ("Name", "Tracker", None),
            ("ParameterControlType", "22", None),
            ("ParameterID", "6", None),
            ("StartKeyframePosition", "-91445760000000000", None),
            (
                "StartKeyframeValue",
                "AQAAAAAAgD8AAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAACAPwAAgD8AAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAIA/AACAPwAAAAA=\n\t\t",
                {
                    "Encoding": "base64",
                    "BinaryHash": "11d96c46-af5b-7d09-d31f-ff4d00000074",
                },
            ),
        ),
    ),
    (
        "ArbVideoComponentParam",
        "313e54d4-6903-49ad-b0bf-8262cdd10f4e",
        "3",
        (
            ("Name", "Tracker", None),
            ("ParameterControlType", "22", None),
            ("ParameterID", "24", None),
            ("StartKeyframePosition", "-91445760000000000", None),
            (
                "StartKeyframeValue",
                "DAAAAAgADAAEAAgACAAAABgAAABMAAAAEAAMAAAAAAAAAAcAAAAIABAAAAAAAAAABAAAACQAAABhOTQwZDhhNS1mNmI2LTRhMTgtYTFiYi0wNzhjNmY3OGZiOTgAAAAAAAAAAA==\n\t\t",
                {
                    "Encoding": "base64",
                    "BinaryHash": "699b5dd3-53cf-a7cd-016f-779b00000070",
                },
            ),
        ),
    ),
    (
        "ArbVideoComponentParam",
        "313e54d4-6903-49ad-b0bf-8262cdd10f4e",
        "3",
        (
            ("Name", "Path", None),
            ("ParameterControlType", "22", None),
            ("ParameterID", "7", None),
            ("StartKeyframePosition", "-91445760000000000", None),
            (
                "StartKeyframeValue",
                "AgAAAAAAAAA=\n\t\t",
                {
                    "Encoding": "base64",
                    "BinaryHash": "5b3d1e1b-2b68-8c23-e1d2-827a00000014",
                },
            ),
        ),
    ),
    (
        "VideoComponentParam",
        "cc12343e-f113-4d3b-ae05-b287db77d461",
        "10",
        (
            ("Name", "Transform", None),
            ("ParameterControlType", "11", None),
            ("ParameterID", "8", None),
            ("StartKeyframe", "-91445760000000000,false,0,0,0,0,0,0", None),
            ("UpperBound", "false", None),
        ),
    ),
    (
        "PointComponentParam",
        "ca81d347-309b-44d2-acc7-1c572efb973c",
        "4",
        (
            ("Name", "Position", None),
            ("ParameterID", "9", None),
            ("StartKeyframe", "-91445760000000000,0:0,0,0,0,0,0,0,5,4,0,0,0,0", None),
        ),
    ),
    (
        "PointComponentParam",
        "ca81d347-309b-44d2-acc7-1c572efb973c",
        "4",
        (
            ("Name", "Scale", None),
            ("ParameterID", "11", None),
            ("StartKeyframe", "-91445760000000000,1:1,0,0,0,0,0,0,5,4,0,0,0,0", None),
        ),
    ),
    (
        "VideoComponentParam",
        "a4ff2d6e-7ac2-44f8-9d52-17d9ca50e542",
        "10",
        (
            ("Name", "Scale Height", None),
            ("LowerUIBound", "0", None),
            ("UpperUIBound", "200", None),
            ("ParameterID", "26", None),
            ("StartKeyframe", "-91445760000000000,100.,0,0,0,0,0,0", None),
            ("LowerBound", "-5000", None),
            ("UpperBound", "5000", None),
        ),
    ),
    (
        "VideoComponentParam",
        "a4ff2d6e-7ac2-44f8-9d52-17d9ca50e542",
        "10",
        (
            ("Name", "Scale Width", None),
            ("LowerUIBound", "0", None),
            ("UpperUIBound", "200", None),
            ("ParameterID", "27", None),
            ("StartKeyframe", "-91445760000000000,100.,0,0,0,0,0,0", None),
            ("LowerBound", "-5000", None),
            ("UpperBound", "5000", None),
        ),
    ),
    (
        "VideoComponentParam",
        "cc12343e-f113-4d3b-ae05-b287db77d461",
        "10",
        (
            ("Name", "Uniform Scale", None),
            ("ParameterID", "28", None),
            ("StartKeyframe", "-91445760000000000,false,0,0,0,0,0,0", None),
        ),
    ),
    (
        "VideoComponentParam",
        "fe47129e-6c94-4fc0-95d5-c056a517aaf3",
        "10",
        (
            ("Name", "Rotation", None),
            ("ParameterControlType", "3", None),
            ("ParameterID", "12", None),
            ("StartKeyframe", "-91445760000000000,0.,0,0,0,0,0,0", None),
            ("LowerBound", "-32768", None),
            ("UpperBound", "32767", None),
        ),
    ),
    (
        "PointComponentParam",
        "ca81d347-309b-44d2-acc7-1c572efb973c",
        "4",
        (
            ("Name", "Anchor Point", None),
            ("ParameterID", "10", None),
            ("StartKeyframe", "-91445760000000000,0:0,0,0,0,0,0,0,5,4,0,0,0,0", None),
        ),
    ),
    (
        "VideoComponentParam",
        "cc12343e-f113-4d3b-ae05-b287db77d461",
        "10",
        (
            ("ParameterControlType", "12", None),
            ("ParameterID", "13", None),
            ("StartKeyframe", "-91445760000000000,false,0,0,0,0,0,0", None),
            ("UpperBound", "false", None),
        ),
    ),
    (
        "VideoComponentParam",
        "a4ff2d6e-7ac2-44f8-9d52-17d9ca50e542",
        "10",
        (
            ("Name", "Feather", None),
            ("UpperUIBound", "300", None),
            ("ParameterID", "14", None),
            ("StartKeyframe", "-91445760000000000,0.,0,0,0,0,0,0", None),
            ("LowerBound", "0", None),
            ("UpperBound", "5000", None),
        ),
    ),
    (
        "VideoComponentParam",
        "a4ff2d6e-7ac2-44f8-9d52-17d9ca50e542",
        "10",
        (
            ("Name", "Opacity", None),
            ("ParameterID", "15", None),
            ("StartKeyframe", "-91445760000000000,100.,0,0,0,0,0,0", None),
            ("LowerBound", "0", None),
            ("UpperBound", "100", None),
        ),
    ),
    (
        "VideoComponentParam",
        "a4ff2d6e-7ac2-44f8-9d52-17d9ca50e542",
        "10",
        (
            ("Name", "Expansion", None),
            ("LowerUIBound", "-300", None),
            ("UpperUIBound", "300", None),
            ("ParameterID", "16", None),
            ("StartKeyframe", "-91445760000000000,0.,0,0,0,0,0,0", None),
            ("LowerBound", "-5000", None),
            ("UpperBound", "5000", None),
        ),
    ),
    (
        "VideoComponentParam",
        "cc12343e-f113-4d3b-ae05-b287db77d461",
        "10",
        (
            ("ParameterID", "17", None),
            ("StartKeyframe", "-91445760000000000,false,0,0,0,0,0,0", None),
        ),
    ),
    (
        "VideoComponentParam",
        "a4ff2d6e-7ac2-44f8-9d52-17d9ca50e542",
        "10",
        (
            ("ParameterID", "25", None),
            ("StartKeyframe", "-91445760000000000,32.,0,0,0,0,0,0", None),
            ("LowerBound", "0", None),
            ("UpperBound", "192", None),
        ),
    ),
    (
        "VideoComponentParam",
        "6e02e8bb-2569-46b2-8ab1-4ab11c43e9c8",
        "10",
        (
            ("Name", "Blend Mode", None),
            ("DiscontinuousInterpolate", "true", None),
            ("ParameterID", "21", None),
            ("StartKeyframe", "-91445760000000000,0,0,0,0,0,0,0", None),
            ("LowerBound", "0", None),
            ("UpperBound", "2", None),
        ),
    ),
    (
        "VideoComponentParam",
        "6e02e8bb-2569-46b2-8ab1-4ab11c43e9c8",
        "10",
        (
            ("Name", "Type", None),
            ("ParameterControlType", "10", None),
            ("DiscontinuousInterpolate", "true", None),
            ("ParameterID", "22", None),
            ("StartKeyframe", "-91445760000000000,0,0,0,0,0,0,0", None),
            ("LowerBound", "0", None),
            ("UpperBound", "4", None),
        ),
    ),
    (
        "ArbVideoComponentParam",
        "313e54d4-6903-49ad-b0bf-8262cdd10f4e",
        "3",
        (
            ("Name", "User Interactions", None),
            ("ParameterControlType", "22", None),
            ("ParameterID", "23", None),
            ("StartKeyframePosition", "-91445760000000000", None),
            (
                "StartKeyframeValue",
                "EAAAAAAACgAMAAAABAAIAAoAAAAIAAAADAAAAAAAAAAAAAAAAAAAAA==\n\t\t",
                {
                    "Encoding": "base64",
                    "BinaryHash": "78e643da-f62d-ea4a-5b5e-85c500000034",
                },
            ),
        ),
    ),
)

#: The SelectionComponents chain object shape and where the
#: reference sits among the track item's children.
SELECTION_CHAIN = (
    "VideoComponentChain",
    "0970e08a-f58f-4108-b29a-1a717b8e12e2",
    "3",
    (("ComponentChain", {"Version": "3"}, ["Components"]),),
)
TRACK_ITEM_ORDER = (
    "ClipTrackItem",
    "SelectionComponents",
    "PixelAspectRatio",
    "ToneMapSettings",
    "FrameRect",
)
